### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by srosam** [pixel-point/kube-forwarder#44]
I'm following the instructions under "installing" however when running "npm run dev" I get 

Error: Application entry file "dist\electron\main.js" in the "C:\git\kube-forwarder\build\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.

Any clues as to what might be wrong.. apart from the obvious :-)

**Comment by FritschAuctores** [comment]
Same error here:
```
  • electron-builder version=20.41.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build\builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=5.0.6 appOutDir=build\win-unpacked
Error: Application entry file "dist\electron\main.js" in the "c:\Temp\kube-forward\kube-forwarder\build\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
    at error (c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\out\asar\asarFileChecker.js:44:15)
    at c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:30:4
    at Generator.next (<anonymous>)
    at c:\Temp\kube-forward\kube-forwarder\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at _checkFileInArchive (c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:36:17)
    at checkFileInArchive (c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\out\asar\asarFileChecker.js:40:30)
    at c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\platformPackager.ts:409:13
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.checkFileInPackage (c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\platformPackager.ts:406:110)
    at c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\platformPackager.ts:460:16
    at Generator.next (<anonymous>)
    at c:\Temp\kube-forward\kube-forwarder\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at WinPackager.sanityCheckPackage (c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\platformPackager.ts:446:92)
    at c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\platformPackager.ts:249:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at WinPackager.doPack (c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
    at c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
    at c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (c:\Temp\kube-forward\kube-forwarder\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at c:\Temp\kube-forward\kube-forwarder\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\packager.ts:396:24)
    at c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at c:\Temp\kube-forward\kube-forwarder\node_modules\graceful-fs\graceful-fs.js:111:16
    at c:\Temp\kube-forward\kube-forwarder\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\packager.ts:335:133)
    at c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Packager.build (c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (c:\Temp\kube-forward\kube-forwarder\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (c:\Temp\kube-forward\kube-forwarder\node_modules\electron-builder\src\builder.ts:228:10)
    at then (c:\Temp\kube-forward\kube-forwarder\node_modules\electron-builder\src\cli\cli.ts:49:19)
```

**Comment by dobesv** [comment]
I bet the build doesn't work in Windows, maybe try in Linux / macOS (can use a VM to run Linux).
